In [ ]:
from google.colab import files
uploaded1=files.upload()

Saving testst.csv to testst (1).csv


In [ ]:
import pandas as pd
moist=pd.read_csv("testst (1).csv");

In [ ]:
moist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   TM      2399 non-null   float64
 1   HM      2399 non-null   float64
 2   CT      2399 non-null   object 
 3   PT      2399 non-null   float64
 4   SM      2399 non-null   float64
dtypes: float64(4), object(1)
memory usage: 93.8+ KB


In [ ]:
moist["CT"].value_counts()

grapes          300
rice            300
Ground Nut      200
Jute            200
maize           200
papaya          200
Tea             200
watermelon      200
wheat           200
Kidney Beans    100
millet          100
Pigeon Peas     100
muskmelon        99
Name: CT, dtype: int64

In [ ]:
moisture = moist.copy()
moisture.replace({'CT':{'grapes':0,'rice':1, 'Ground Nut':2,'Jute':3,'maize':4,'papaya':5 ,'Tea':6,'watermelon':7,'wheat':8,'Kidney Beans':9,'millet':10,'Pigeon Peas':11,'muskmelon':12}}, inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(moisture, test_size=0.2,random_state=42)
print(f"The rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")

The rows in train set: 1919
Rows in test set: 480



In [ ]:
train_set.count()
test_set.count()

TM    480
HM    480
CT    480
PT    480
SM    480
dtype: int64

In [ ]:
train_set_tr = train_set.drop("SM",axis=1)
moisture_labels = train_set["SM"].copy()

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(train_set_tr.values,moisture_labels.values)

RandomForestRegressor()

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Create and fit the RandomForestRegressor model
model = RandomForestRegressor()
model.fit(train_set_tr.values, moisture_labels.values)

# Predict on the training set
y_pred_rf = model.predict(train_set_tr.values)

# Calculate regression metrics
mse = mean_squared_error(moisture_labels, y_pred_rf)
rmse = mean_squared_error(moisture_labels, y_pred_rf, squared=False)
mae = mean_absolute_error(moisture_labels, y_pred_rf)
r2 = r2_score(moisture_labels, y_pred_rf)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")


Mean Squared Error (MSE): 2.62
Root Mean Squared Error (RMSE): 1.62
Mean Absolute Error (MAE): 1.28
R-squared (R2) Score: 1.00


In [ ]:
# 1 2 3 4 5 6 7 8 9 10
import numpy as np
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,train_set, moisture_labels, scoring="neg_mean_squared_error", cv=10)
rmse_scores= np.sqrt(-scores)

In [ ]:
rmse_scores

array([0.03945939, 0.04343519, 0.05335958, 0.04393909, 0.04005442,
       0.0336768 , 0.04475073, 0.04690888, 0.04241261, 0.04593957])

In [ ]:
def print_scores(scores):
    print("Scores:",scores)
    print("Mean:",scores.mean())
    print("Standard deviation:",scores.std())

In [ ]:
print_scores(rmse_scores)

Scores: [0.03871427 0.04264107 0.05250274 0.04366113 0.0428172  0.03298837
 0.04687033 0.04635348 0.04932614 0.04674557]
Mean: 0.04426203118903446
Standard deviation: 0.005233060020109394


In [ ]:
from joblib import dump,load
dump(model,'new.joblib')

['new.joblib']

In [ ]:
from joblib import dump,load
import numpy as np
model=load('new.joblib')

In [ ]:
import numpy as np
input = np.array([[29.00,79.00,1,0]])
model.predict(input)

array([71.0354])

In [ ]:
uploaded2=files.upload()

Saving testing_dataset.csv to testing_dataset.csv


In [ ]:
import pandas as pd
D= pd.read_csv("testing_dataset.csv")
F=D['SM'].copy
d=D.drop('SM',axis=1)
d.replace({'CT':{'grapes':0,'rice':1, 'Ground Nut':2,'Jute':3,'maize':4,'papaya':5,'Tea':6,'watermelon':7,'wheat':8,'Kidney Beans':9,'millet':10,'Pigeon Peas':11,'muskmelon':12}}, inplace=True)

In [ ]:
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

model = joblib.load('new.joblib')

print("The Testing Dataset head:")
print(D.head())
print()
print("Making predictions for the testing dataset head:")
print(d.head())
print("The predictions are")
print(model.predict(d.head()))

The Testing Dataset head:
          TM         HM          CT     PT     SM
0  26.275206  86.632496  watermelon   3.96   7.27
1  41.728857  15.242983      millet   0.72  23.87
2  26.379785  91.488895      grapes   0.00  74.24
3  24.605322  73.588685       maize   0.00  75.36
4  29.008124  84.960894   muskmelon  21.56  11.06

Making predictions for the testing dataset head:
          TM         HM  CT     PT
0  26.275206  86.632496   7   3.96
1  41.728857  15.242983  10   0.72
2  26.379785  91.488895   0   0.00
3  24.605322  73.588685   4   0.00
4  29.008124  84.960894  12  21.56
The predictions are
[ 7.8699 19.6685 72.1994 71.6483 10.7297]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


In [ ]:
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

model = joblib.load('new.joblib')

print("The Testing Dataset:")
print(D)
print("The result set ")
print(model.predict(d))

The Testing Dataset:
            TM         HM          CT     PT     SM
0    26.275206  86.632496  watermelon   3.96   7.27
1    41.728857  15.242983      millet   0.72  23.87
2    26.379785  91.488895      grapes   0.00  74.24
3    24.605322  73.588685       maize   0.00  75.36
4    29.008124  84.960894   muskmelon  21.56  11.06
..         ...        ...         ...    ...    ...
475  28.636281  84.614311   muskmelon   0.00   9.21
476  22.037342  64.082634  watermelon  12.58  12.88
477  26.220060  80.901270  watermelon   8.48  10.48
478  29.066094  79.015231         Tea   2.53  31.21
479  33.490771  62.733172  Ground Nut   0.00  49.18

[480 rows x 5 columns]
The result set 
[ 7.9485 19.1141 72.4207 71.6947 10.6766  8.665   9.7468 65.7806 86.5135
 18.3598 42.5571 44.0006 46.9344 76.2265 67.6644 65.4974 29.4456 70.6424
 34.4063 46.3826 65.043  14.4466 34.9994 37.8274 72.025  47.2446 40.1985
 77.6469 38.9524 68.5406 68.6869 45.2122 80.073  68.9699 67.509  67.4896
 68.9132 42.9309 32.331

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


In [ ]:
import requests
import urllib. request
import numpy as np
import joblib
import time
import json

In [ ]:
uploaded3=files.upload()

In [ ]:
# Path to the trained joblib ML model
#model_path =r"C:\Users\avd83\Documents\Farm\Test(MQTT)\new.joblib"
# Load the ML model
model = joblib.load("new.joblib")
print(model)

RandomForestRegressor()


In [ ]:
def fetch_precipitation_data(API_KEY,city_name):

  latitude = '22.5697'
  longitude = '88.3697'


  # OpenWeatherMap API endpoint URL
  API_URL = f'http://api.openweathermap.org/data/2.5/weather?q={city_name}&lat={latitude}&lon={longitude}&appid={API_KEY}'

  # Make the API request
  response = requests.get(API_URL)

  if response.status_code == 200:
    data = response.json()

    # Extract precipitation data
    precipitation = data.get('rain', 0)
    return precipitation
  else:
    print('Error:', response.status_code)



In [ ]:
def thingspeak_publish(val1):
  API_URL = "https://api.thingspeak.com/update.json"

  # ThingSpeak Channel API Key (Replace with your actual API Key)
  API_KEY = "UJNR6LH8E6MJ2CRY"

  # Data to be sent (Replace with your data)
  data = {
    "api_key": API_KEY,
    "field5": val1,  # Example data for Field 5
  }

  # Send POST request to ThingSpeak API
  response = requests.post(API_URL, data=data)

  # Check the response
  if response.status_code == 200:
    print("Data sent successfully to ThingSpeak!")
  else:
    print("Failed to send data to ThingSpeak. Status code:", response.status_code)

In [ ]:
def isnan(num):
    return num!=num

result=[0.00,0.00]

In [ ]:
def thinkspeak_subscribe():
  channel_id = "2237283"
  read_api_key = "YJOSAN7USB22WPHTJ"

  # URL to retrieve data from ThingSpeak
  url = f"https://api.thingspeak.com/channels/{channel_id}/feeds.json?api_key={read_api_key}&results=1"
  # Make the GET request
  response = requests.get(url)
  # Check if the API request was successful
  if response.status_code == 200:
    # Extract the latest temperature and humidity values
    data = response.json()
    entries = data["feeds"]
    print(entries)
    if len(entries) > 0:
      try:
        if entries[0].get("field1")!=None and entries[0].get("field2")!=None:
          result[0] = entries[0].get("field1")
          result[1] = entries[0].get("field2")
      except:
        pass
    else:
      print("No data available.")
  else:
    print("Failed to fetch data. Error code:", response.status_code)

In [ ]:
i=1
API_KEY = '5c48b55a7a5324e2366077387fcdc16a'
# Replace with the city name
city_name = 'Kolkata,IN'

while True:
    precipitation=fetch_precipitation_data(API_KEY,city_name)
    #Print the precipitation data
    if precipitation is not None:
        print(f"Precipitation: {precipitation} mm")

    thinkspeak_subscribe()
    print("temperature:  ",result[0])
    print("humidity: ",result[1])
    # Preprocess the data
    data = np.array([[result[0], result[1],1,precipitation]] )
    # Apply the ML model for prediction
    prediction=model.predict(data)
    prediction=float(prediction)
    print(f"Prediction:{prediction} %")
    thingspeak_publish(prediction)
    time.sleep(10)
    i+=1

Precipitation: 0 mm
[{'created_at': '2023-08-19T08:03:49Z', 'entry_id': 547, 'field1': '27.50', 'field2': '63.00\r\n\r\n', 'field3': None, 'field4': None, 'field5': None}]
temperature:   27.50
humidity:  63.00


Prediction:71.9078 %


KeyboardInterrupt: ignored